env:
  - any: ["*"]
    all: ["!README.md"]

front-end:
  - **/*.tsx

firebase:
  - src/firebase/*

i18n:
  - any: ["src/locales/*", "src/locale.ts"]

doc:
  - README.md

dependencies:
  - any: ["package*.json"]
